name: Continuous Integration for server backend

on:
    push:
      branches:
        - dev
        # Add another branches if required
  
    pull_request:
      branches:
        - main
        # Add another branches if required

jobs: 
    lint_and_test: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: install dependencies
              run: |
                cd app
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: lint
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: unit test
              run: |
                python -m unittest discover